### ISSUE TITLE
Error when starting homebridge

### ISSUE THREAD

**Issue by Jasperschn** [jochem725/homebridge-toon#19]
Goedenavond,

Zojuist de plugin geïnstalleerd en de config file aangepast. Echter krijg ik de volgende foutcode.
Het zegt mij niet heel veel, wellicht weet iemand wat er mis gaat?

Groet Jasper

pi@raspberrypi:~ $ homebridge
[2018-12-19 20:12:14] Loaded config.json with 2 accessories and 1 platforms.
[2018-12-19 20:12:14] ---
[2018-12-19 20:12:15] Loaded plugin: homebridge-sonos
[2018-12-19 20:12:15] Registering accessory 'homebridge-sonos.Sonos'
[2018-12-19 20:12:15] ---
[2018-12-19 20:12:16] Loaded plugin: homebridge-toon
[2018-12-19 20:12:16] Registering accessory 'homebridge-toon.Toon'
[2018-12-19 20:12:16] ---
[2018-12-19 20:12:16] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Toon' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45) 
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by rbeniers** [comment]
Hoi Jasper,

Ik heb hetzelfde probleem.

Is hier een oplossing voor?

**Comment by rbeniers** [comment]
Issue solved.

The link from Homebridge to the plug-in shows a configuration for Toon as a platform. This will not work.
Configuring Toon as accessory will do the trick! Just add this to the config.json:

{
  "accessories": [
    {
      "accessory": "Toon",
      "name": "NAME",
      "username": "TOONOPAFSTAND USERNAME",
      "password": "TOONOPAFSTAND PASSWORD"
    }
  ]
}
