### ISSUE TITLE
Werkt Hombrige-toon plugin nog?

### ISSUE THREAD

**Issue by tjimmychanga** [jochem725/homebridge-toon#22]
Weet iemand of dat de Hombridge-toon plugin nog werkt?

Ik krijg steeds Error: Authentication error 401 en heb al van alles geprobeerd om het te verhelpen. Iemand ideeen?

**Comment by DHoogland** [comment]
Ik vraag het me ook af, ik krijg:
`(node:28769) UnhandledPromiseRejectionWarning: Error: Error while authorizing, please check your credentials.`

Credentials 3x gechecked, die kloppen wel. Wat doe ik verkeerd?

`{
      "platform": "Toon",
      "name": "Thermostaat",
      "username": "mijnusername",
      "password": "wachtwoord",
      "consumerKey": "Gxxxxxxxxxxxxxxxxxxxxxxx4G1yfV",
      "consumerSecret": "DGuxxxxxxxxxxJy9zyG"
    }`

Edit: nevermind, de username en password zijn NIET van developer.toon.eu, maar van 'Mijn Eneco', en de consumer values van developer.toon.eu.

**Comment by DennisDeKoster** [comment]
Homebridge-Toon werkt bij mij al enige tijd uitstekend. Er zit volgens mij verschil tussen de credentials van het Toon API gedeelte en die van MijnEneco. Dit had ik in het begin ook verkeerd, met dezelfde foutmelding tot gevolg. 

-edit- 
Het is al opgelost zie ik :)

**Comment by bolijndotme** [comment]
Ik gebruik deze plugin nu ongeveer een jaar en hij werkt prima! Ik heb er eigenlijk nooit een probleem mee en het werkt snel. 

Wel zie ik dat er dagelijks meerdere keren een `UnhandledPromiseRejectionWarning` optreed, waarbij staat dat het in de huidige versie van NodeJs nog geen probleem is, maar in de toekomst homebridge zal doen crashen; `exit with a non-zero code`. Dat lijkt mij iets wat we voor willen zijn?

Voor nu werkt alles dus prima, maar als ik het goed begrijp kan dit in de toekomst een probleem worden. Ik zal dat in een nieuw ‘issue’ melden, inclusief de logs. 

Groet,
Michel

**Comment by loewal** [comment]
Hier dus nu gecrashed met bovenstaande opmerking. Toon is niet meer bereikbaar.
Iemand????

**Comment by gielk** [comment]
> Hier dus nu gecrashed met bovenstaande opmerking. Toon is niet meer bereikbaar.
> Iemand????

Ik heb hetzelfde probleem!
Krijg de volgende meldingen.


```
[2020-2-21 07:41:29] [Toon] Current Target Temperature:  undefined
[2020-2-21 07:41:31] [Toon] Current Temperature:  undefined
```

```
(node:5626) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "\n         <!doctype html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"UTF-8\">\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n        <title>Invalid redirect_uri</title>\n \n        <style>\n            @import url(https://fonts.googleapis.com/css?family=Open+Sans);\n            @import url(https://fonts.googleapis.com/css?family=Roboto);\n \n            *:focus {\n                outline: none;\n            }\n \n            body {\n                background-color: #fff;\n                color: #43484d;\n                font-family: 'FFClanWebNews', 'Helvetica Neue', 'Helvetica', 'Roboto', 'Arial', sans-serif;\n                font-size: 1.4rem;\n                margin: 0;\n            }\n            main {\n                margin:42px auto;\n                text-align:center;\n                width: 480px;\n            }\n            a, a:active  {\n                color: #D7242A;\n                text-decoration: none;\n            }\n            a:visited {\n                color: #701317;\n            }\n            .page-header {\n                background-color: #D7242A;\n                height: 10px;\n                \n                background-position: center;\n            }\n \n            h1 {\n                font-family: 'Open Sans', sans-serif;\n                font-size: 20px;\n            }\n \n            h2 {\n                font-size: 16px;\n            }\n \n            .viesgo {\n                color: #D7242A;\n                font-weight: 900;\n            }\n            .field {\n                margin:20px auto;\n                width:340px;\n            }\n            .error {\n                color:red;\n                display:none;\n                font-weight:bold;\n            }\n            .error.true {\n                display:block;\n            }\n            label {\n                display:block;\n                font-size: 12px;\n                text-align:left;\n            }\n \n            input,\n            select {\n                border:1px solid #a0b1b9;\n                font-size:14px;\n                height:32px;\n                margin-top:4px;\n                width:100%;\n            }\n            input:not([type=submit]) {\n                background-color: transparent;\n                border: 0;\n                border-bottom: 1px solid #414141;\n                height: 32px;\n            }\n            input:not([type=submit]):focus {\n                border-bottom-color: #cccccc;\n            }\n \n            ::-webkit-input-placeholder {\n                font-style: italic;\n            }\n \n            :-moz-placeholder { /* Firefox 18- */\n                font-style: italic;\n            }\n \n            ::-moz-placeholder {  /* Firefox 19+ */\n                font-style: italic;\n            }\n \n            :-ms-input-placeholder {\n                font-style: italic;\n            }\n \n            .button {\n                background-color: #D7242A;\n                border:0;\n                box-shadow: 0 4px 0 0 #701317;\n                color: #ffffff;\n                cursor: pointer;\n                height: 50px;\n                line-height: 50px;\n                margin: 30px auto;\n                padding:0;\n                width: 280px;\n            }\n \n            @media (min-width: 322px) and (max-width: 480px) {\n                .page-content {\n                    margin:2%;\n                    width:96%;\n                }\n                .field {\n                    margin:20px 10%;\n                    width:80%;\n                }\n            }\n            @media (max-width: 321px) {\n                .page-content {\n                    margin:2%;\n                    width:96%;\n                }\n                .field {\n                    margin:20px 0;\n                    width:280px;\n                }\n            }\n        </style>\n    </head>\n    <body>\n        <header class=\"page-header\"></header>\n        <main class=\"page-content\">\n            <h1>Developer hint:</h1>\n            <p>The requested redirect_uri does not match any of the whitelisted redirect_uris on the Toon developer page.</p>\n            <p>Make sure to allow the requested redirect_uri on your registered Toon app in the <a href=\"https://developer.toon.eu/\">developer pages</a></p>\n            <p>Multiple redirect_uris can be used, separated by a comma.</p>\n        </main>\n    </body>\n</html>\n \n            "
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
(node:5626) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5626) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
