### ISSUE TITLE
<N00b-alert> - Ik krijg het maar niet werkend...

### ISSUE THREAD

**Issue by Robmanzzz** [jochem725/homebridge-toon#25]
Hallo iedereen,

Het zal wel een supersimpele oplossing zijn, maar ik heb het nu al een paar keer van scratch geprobeerd om het aan de gang te krijgen. Ik krijg de volgende fout tijdens het opstarten van Homebridge:

[12/28/2019, 10:24:14 PM] [Toon] Toon Initialized, it may take a few minutes before any data will be visible to HomeKit.
[12/28/2019, 10:24:14 PM] Homebridge is running on port 51826.
(node:58757) UnhandledPromiseRejectionWarning: Error: Error while authorizing, please check your credentials.
    at ToonConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/dist/src/Toon/ToonConnection.js:158:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-toon/dist/src/Toon/ToonConnection.js:4:58)
(node:58757) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58757) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

De API-credentials zijn goed, deze werken namelijk wel in de Home Assistant plugin (nee deze staat niet tegelijk aan, ik heb het alleen getest of het misschien daar aan lag).

Ik dacht eerst dat de plugin gewoon niet meer werkte maar ik heb recente berichten op deze pagina gelezen van mensen die het gewoon werkend hebben...

Dank alvast!

Rob

**Comment by Robmanzzz** [comment]
Goed, opgelost. Het bleken de tekens in mijn wachtwoord te zijn...
