### ISSUE TITLE
Foutmelding Homebridge-toon (node:30621) UnhandledPromiseRejectionWarning: Error: Error while authorizing, please check your credentials.

### ISSUE THREAD

**Issue by SiddLord93** [jochem725/homebridge-toon#27]
Hoi,
Ik heb mijn oude raspberry 2 vervangen door de 4B. Sinds ik de 4B heb draaien krijg ik de volgende foutmelding. En ja ik heb mijn login gegevens 100x gecontroleerd. hebben jullie enig idee?

(node:30621) UnhandledPromiseRejectionWarning: Error: Error while authorizing, please check your credentials.
    at ToonConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/dist/src/Toon/ToonConnection.js:158:27)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/homebridge-toon/dist/src/Toon/ToonConnection.js:4:58)
(node:30621) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Peet-B** [comment]
Ik heb precies hetzelfde probleem, en dit komt denk ik door de nieuwe API die langzaamaan doorgevoerd wordt. Ik kan al een aantal weken mijn Toon niet meer via Homekit bedienen, en zo ver ik weet is hier ook geen andere oplossing voor...

**Comment by dannyharuh** [comment]
sinds vandaag heb ik helaas ook hetzelfde probleem hopelijk kan dit opgelost worden door iemand

**Comment by DHoogland** [comment]
Ik heb er wel genoeg van eigenlijk. Elke maand wel betalen voor de diensten, maar we krijgen er na mijn mening niet genoeg voor terug. Afgelopen 3 jaar heb ik niks nieuws zien komen voor Toon. Leuk, een verspillings checker in de app, maar ik had graag meer functionaliteit gezien voor een "smart home".

Maar goed, misschien dat ik later deze week tijd heb om te kijken wat er niet goed gaat hier.

**Comment by Peet-B** [comment]
Ik ben er ook klaar mee inderdaad, ik ga binnenkort kijken of ik ‘m kan rooten, maar alle “handleidingen” zijn van een aantal jaar terug...

**Comment by SiddLord93** [comment]
Vervelend allemaal. Als dit te veel tijd kost of de veranderingen zijn het niet waard. Word het toch tijd om 
te kijken voor een alternatief. 
Hebben jullie enige ervaring met een thermostaat die ook de P1 porten?(een waardige toon vervanging. )

**Comment by wtrdk** [comment]
Ondanks deze foutmelding, die ik dus ook krijg, werkt Toon prima met Homebridge/HomeKit via deze plugin.

Volledige foutmelding:

```
(node:593290) UnhandledPromiseRejectionWarning: StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (/usr/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:593290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 55)
(node:593290) UnhandledPromiseRejectionWarning: StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (/usr/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:593290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 56)
```
