### ISSUE TITLE
Losing Toon connection

### ISSUE THREAD

**Issue by SonicRevolutions** [jochem725/homebridge-toon#3]
Homebridge is losing Toon connection after a certain amount of time. Restarting the homebridge process will login to the Toon site again and things will work as it should.

Is this a known issue?

**Comment by jochem725** [comment]
@SonicRevolutions I've only been using the plugin to read the temperature lately, so I haven't noticed this issue. I've seen this issue before, but I could not replicate it so I created #2.  After running some tests this week it appears reading temperature values always works, but after some time setting the temperature stops working. 

Is this the same behaviour you are experiencing?

**Comment by SonicRevolutions** [comment]
@jochem725 once the connection is gone mine doesn't get the correct temperature info either.

**Comment by jochem725** [comment]
@SonicRevolutions I think I've found the issue. I'm working on a fix, but I am unable to test it because there appears to be a failure of the Toon server. If the server issues are resolved, I'll publish a test branch so you can check if thinks work correctly again.

**Comment by matthijsotterloo** [comment]
@jochem725 Is the test branch ready yet?

**Comment by jochem725** [comment]
@matthijsotterloo, @SonicRevolutions I've just finished a complete rewrite of the plugin, it can be found at #4 including an `npm install` link to test. Sometimes the connection may be unstable, since the issues at the Toon op Afstand servers still persist. Please let me know if this improves things.

**Comment by matthijsotterloo** [comment]
@jochem725 Great! Will try this tonight. Yesterday I kept getting the notice that it had to be initialized first. Is this a bug in the script or has it something to do with the Toon op Afstand server issues?

**Comment by jochem725** [comment]
@matthijsotterloo I think a combination of both is the case. I haven't been using the plugin for a while myself, but after looking into the issues I decided it was better to rewrite the thing. I'm no longer seeing any connection issues to my Toon, so thats already a major improvement.

**Comment by matthijsotterloo** [comment]
@jochem725 It works! Altough I sometimes get some weird error in my console.

`Error: Received invalid response from Toon
 +undefined
    at /usr/local/lib/node_modules/homebridge-toon/toon.js:148:27
    at tryCatcher (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:636:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)`

**Comment by matthijsotterloo** [comment]
And now I get "{"success":false,"reason":"Display already has max number of clients: 4","errorCode":"couldNotRegisterAsListenerForDisplay"}"

**Comment by jochem725** [comment]
@matthijsotterloo I have not yet encountered the first error, not sure what causes it. The second response is returned when too many applications are logged in to Toon op Afstand, mostly happens after restarting, since it does not log out if Homebridge terminates.

**Comment by SonicRevolutions** [comment]
Connections issues seem fixed. I also receive the invalid response error but it's working properly.

**Comment by jochem725** [comment]
@matthijsotterloo @SonicRevolutions I've managed to resolved the first issue, it appears that the server sends only a header with a success statuscode, but no data if there are no changes to report. Reinstalling the fix branch should solve your issues. I was unable to resolve the `Display already has max number of clients` problem. It only occurs for me after multiple restarts of the plugin in a short time but I cannot prevent this.

**Comment by SonicRevolutions** [comment]
Works perfect for me. @matthijsotterloo close the issue?

**Comment by jochem725** [comment]
If @matthijsotterloo no longer has any issues with #4, I'll publish the new version to `npm`.

**Comment by matthijsotterloo** [comment]
Yes, close the issue and push to npm! @jochem725

**Comment by jochem725** [comment]
I've published the new version to `npm`. Thanks for helping out @SonicRevolutions, @matthijsotterloo
