### ISSUE TITLE
Sigterm error door toon?

### ISSUE THREAD

**Issue by jednl** [jochem725/homebridge-toon#35]
Ik krijg een error van de toon module. Resultaat hiervan is dat homebridge zich elk half uur (ongeveer) herstart.

[12/8/2021, 8:19:19 PM] RequestError: Error: getaddrinfo EAI_AGAIN api.toon.eu
    at new RequestError (/homebridge/node_modules/homebridge-toon/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/homebridge/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/homebridge/node_modules/homebridge-toon/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/homebridge/node_modules/homebridge-toon/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.onRequestError (/homebridge/node_modules/homebridge-toon/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Iemand een idee waar dit door komt?

**Comment by unequalsine** [comment]
Yes ook last van, soms gaat het herstarten zelfs een stuk frequenter (elke minuut)

**Comment by gielk** [comment]
Zelfde ook last van. Homebridge kan nu niet meer blijven draaien met toon plug-in. Heb de plug-in nu gedeactiveerd. 
![574F0C11-821C-4C43-8D8C-29BB19F283D6](https://user-images.githubusercontent.com/24224715/147400879-48a9ae4e-78f8-4305-a5de-48c75310c2d8.jpeg)

Hoop dat dit probleem snel opgelost kan worden.

**Comment by gielk** [comment]
Toon HomeKit is nu onbruikbaar geworden @jochem725 Zou je hier naar kunnen kijken,.

**Comment by jednl** [comment]
Ik ben overgestapt naar homebridge-toon-platform. Die werkt (na installatie van node-fetch) zonder issue's.

**Comment by gielk** [comment]
> Ik ben overgestapt naar homebridge-toon-platform. Die werkt (na installatie van node-fetch) zonder issue's.

Thanks ik ga hier naar kijken.

**Comment by ruudbol** [comment]
Ik ben ook overgestapt naar homebridge-toon-platform versie 0.9.6 werkt goed, 0.9.7 werkt bij mij niet. @jochem bedankt voor vele jaren TOON plugin.

**Comment by gielk** [comment]
Indeed @jochem725 bedankt voor alle tijd en moeite. @ruudbol helaas werkt bij mij 0.9.7 ook niet meer, heeft het wel even gedaan.
