### ISSUE TITLE
error connecting toon with credentials?

### ISSUE THREAD

**Issue by astrapowerrr** [jochem725/homebridge-toon#9]
pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[1/20/2017, 5:21:13 PM] Loaded plugin: homebridge-klikaanklikuit
[1/20/2017, 5:21:13 PM] Registering platform 'homebridge-klikaanklikuit.KlikAanKlikUit'
[1/20/2017, 5:21:13 PM] ---
[1/20/2017, 5:21:14 PM] Loaded plugin: homebridge-toon
[1/20/2017, 5:21:14 PM] Registering accessory 'homebridge-toon.Toon'
[1/20/2017, 5:21:14 PM] ---
[1/20/2017, 5:21:14 PM] Loaded config.json with 1 accessories and 0 platforms.
[1/20/2017, 5:21:14 PM] ---
[1/20/2017, 5:21:14 PM] Loading 1 accessories...
[1/20/2017, 5:21:14 PM] [<Toon>] Initializing Toon accessory...
[1/20/2017, 5:21:14 PM] [<Toon>] Toon Initialized, it may take a few minutes before any data will be visible to HomeKit.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/20/2017, 5:21:14 PM] Homebridge is running on port 51826.
[1/20/2017, 5:21:15 PM] [<Toon>] Retrieving client data from Toon op Afstand...
[1/20/2017, 5:21:15 PM] [<Toon>] Error: There was an error retrieving the client data from Toon.
{"success":false,"reason":"Could not authenticate successfully with given credentials","errorCode":"invalidCredentials"}
    at /usr/lib/node_modules/homebridge-toon/toon.js:113:23
    at tryCatcher (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:636:18)
    at Request._callback (/usr/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-toon/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
^C[1/20/2017, 5:21:23 PM] Got SIGINT, shutting down Homebridge...
pi@raspberrypi:~ $

**Comment by astrapowerrr** [comment]
i also had this error with installing the plugin maybe this is connected to not logging in. 

pi@raspberrypi:~ $ sudo npm install -g homebridge-toon
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
/usr/lib
└── homebridge-toon@0.0.3 

pi@raspberrypi:~ $

**Comment by jochem725** [comment]
@astrapowerrr Maybe you could try #10? If logging in to https://toonopafstand.eneco.nl works, you might have multiple agreements (because your address changed or something like that.) #10 solves this.

**Comment by jochem725** [comment]
@astrapowerrr Glad to hear it's working now 😄
